// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW8w_bTP-rByc_AGuTlXE1mY3td4ah3Ws',
    appId: '1:731970895622:web:aae6c86d67a7dce084a887',
    messagingSenderId: '731970895622',
    projectId: 'credittrust-8b382',
    authDomain: 'credittrust-8b382.firebaseapp.com',
    storageBucket: 'credittrust-8b382.firebasestorage.app',
    measurementId: 'G-QTFSC3841P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUSB5NBh5ISfn6sfRDrXEzisHOqp_UEhI',
    appId: '1:731970895622:android:21dd7a22829f69e384a887',
    messagingSenderId: '731970895622',
    projectId: 'credittrust-8b382',
    storageBucket: 'credittrust-8b382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybwigSYtnyOb6Nc93QRKtRdaICqptMLI',
    appId: '1:731970895622:ios:e5de860b42a1b8a584a887',
    messagingSenderId: '731970895622',
    projectId: 'credittrust-8b382',
    storageBucket: 'credittrust-8b382.firebasestorage.app',
    iosBundleId: 'com.example.creditTrust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybwigSYtnyOb6Nc93QRKtRdaICqptMLI',
    appId: '1:731970895622:ios:e5de860b42a1b8a584a887',
    messagingSenderId: '731970895622',
    projectId: 'credittrust-8b382',
    storageBucket: 'credittrust-8b382.firebasestorage.app',
    iosBundleId: 'com.example.creditTrust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW8w_bTP-rByc_AGuTlXE1mY3td4ah3Ws',
    appId: '1:731970895622:web:b26913f8dae01b0b84a887',
    messagingSenderId: '731970895622',
    projectId: 'credittrust-8b382',
    authDomain: 'credittrust-8b382.firebaseapp.com',
    storageBucket: 'credittrust-8b382.firebasestorage.app',
    measurementId: 'G-HKZGHENSXL',
  );

}